name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.118.2'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Disable host key checking
        run: |
          mkdir -p ~/.ssh
          echo "Host *" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: rsync deployments 2
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -rtv --delete
          path: ./public/*
          remote_path: ~/html
          remote_host: ${{ secrets.NEW_HOST }}
          remote_user: ${{ secrets.NEW_USER }}
          remote_key: ${{ secrets.NEW_SSH_PRIVATE_KEY }}
      - name: rsync deployments 3
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -rtv --delete
          path: ./public/*
          remote_path: ~/html.pw.pdm
          remote_host: ${{ secrets.NEW_HOST }}
          remote_user: ${{ secrets.NEW_USER }}
          remote_key: ${{ secrets.NEW_SSH_PRIVATE_KEY }}
